---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-web-app-tt
spec:
  params: 
  - name: gitrepourl
  - name: gitevision
    default: master
  - name: gitrepoame
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: node-web-app-source-$(uid)
      namespace: node-web-project
    spec:
      params:
      - name: url
        value: $(params.gitrepourl)
      - name: revision
        value: $(params.gitrevision)
      - name: git-repo-name
        value: $(params.gitreponame)
      type: git
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: node-web-app-image-$(uid)
      namespace: node-web-project
    spec:
      params:
      - name: url
        value: 'image-registry.openshift-image-registry.svc:5000/node-web-project/web-node-app:latest'
      type: image
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: node-web-app-pipeline-run-
      namespace: node-web-project
    spec:
      pipelineRef:
        name: node-web-app-pipeline
      resources:
      - name: node-web-app-source
        resourceRef:
          name: node-web-app-source-$(uid)
      - name: node-web-app-image
        resourceRef:
          name: node-web-app-image-$(uid)
      serviceAccountName: pipeline


--- 

apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: node-web-app-tb
spec:
  params:
  - name: gitrepourl
    value: $(body.repository.url)
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitreponame
    value: $(body.repository.name)

---

apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: node-web-app-el
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: node-web-app-tb
    template:
      name: node-web-app-tt

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-node-web-app
  namespace: node-web-project
spec:
  host: el-node-web-app.cpat-poc-travelers-afb9c6047b062b44e3f1b3ecfeba4309-0000.cloud
    sjc03:
      containers:
        appdomain:
          cloud/:
  to:
    kind: Service
    name: el-node-web-app-el
    weight: 100